# Generated by Django 4.2.6 on 2023-12-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='packageType',
            field=models.CharField(choices=[('Website Only', 'Creation or Updating of Website'), ('Add ons', 'Items that can be added on to any package'), ('Maintenance Packages', 'Plans for Website maintenance'), ('All inclusive', 'Starting from the ground up creating and maintaining website')], default='Website Only', max_length=255),
        ),
    ]
