# Generated by Django 4.2.6 on 2023-12-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_service_packagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
