# Generated by Django 4.2.6 on 2024-05-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_info_order_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subPackageType',
            field=models.CharField(choices=[('Public', 'Public Facing Websites'), ('Internal', 'Internal Company Websites')], default='Public', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='packageType',
            field=models.CharField(choices=[('Websites', 'Create or Update websites'), ('Tutoring', 'Tutoring Services'), ('Career', 'Resume and other Career Services'), ('Maintenance', 'Packages for routing website upkeep'), ('Add Ons', 'Items that can be added on to any package'), ('All Inclusive', 'Starting from the ground up creating and maintaining website')], default='Website Only', max_length=255),
        ),
    ]
